### ISSUE TITLE
Help :  Simplier example - From memory-cache to cache-manager

### ISSUE THREAD

**Issue by Shadowman4205** [BryanDonovan/node-cache-manager#101]
Hello i am using  memory-cache and i have got a little hard time to undestand the example with calbacks. I am using for now memory-cache, i want try this too, if anyone can help convert from memory-cache to this package from below example:

```
async function getData(){
        const key = "datas"
    if (cache.get(key)) {
        return cache.get(key);
    } else {
        const routes = await calculateData();
        return cache.put(key, routes, 20 * 60 * 60);
    }
}

const data = getData();
```
this is simple can anyone to convert it to cache manager? Sorry for trouble.

**Comment by BryanDonovan** [comment]
I haven't used `async await` yet, so I'm not sure I can be of much help right now.  I might have time to try this in the next week or so.

**Comment by Shadowman4205** [comment]
what if i remove the async ?

```
function getData(){
        const key = "datas"
    if (cache.get(key)) {
        return cache.get(key);
    } else {
        const routes = calculateData();
        return cache.put(key, routes, 20 * 60 * 60);
    }
}

const data = getData();
```

**Comment by BryanDonovan** [comment]
`cache.get()` returns a promise, so you probably need to do the `then()`, etc. stuff.

**Comment by BryanDonovan** [comment]
Is `calculateData` an async function (I mean does it do I/O, etc.)?

**Comment by Shadowman4205** [comment]
yeah it is for picking data from db.

**Comment by BryanDonovan** [comment]
Is `calculateData` using a `Promise` or `async/await`?

**Comment by Shadowman4205** [comment]
calculateData using feathers js service to get data. 
something like this 
in the calculate data i have got a service that get the data from database it is feathersjs service.
this service return promise so i use 
```
async function calculateData(){
  const data = await feathers.service('/getData')......
  return data;
}
```

**Comment by BryanDonovan** [comment]
Check out the tests starting here: https://github.com/BryanDonovan/node-cache-manager/blob/master/test/caching.unit.js#L31

In particular, this one: https://github.com/BryanDonovan/node-cache-manager/blob/master/test/caching.unit.js#L60

If you're going to use the memory store you can use it synchronously.  But other stores would have to be asynchronous.

**Comment by Shadowman4205** [comment]
Following my example is this possible? (my problem is that i do not understand how callbacks work)
```
function getData() {
    const key = "datas"
    if (memoryCache.get(key )) {
        return memoryCache.get(key );
    }else{
       const result = {"test":"test"}
       memoryCache.set(key , result);
       return memoryCache.get(key );
}
```
