### ISSUE TITLE
Type definitions for Typescript

### ISSUE THREAD

**Issue by nikolayg** [BryanDonovan/node-cache-manager#102]
Hi all,

Are there any type definitions, which I can use in my Typescript code?

Cheers

**Comment by BryanDonovan** [comment]
Hi, I don't use Typescript, so I can't help much here.

**Comment by Deisss** [comment]
It does exists: npm install --save-dev @types/cache-manager (also if you don't know typings install is kind of deprecated for npm @types/something install)
