### ISSUE TITLE
TTL for a never expiring cache

### ISSUE THREAD

**Issue by ajbeach2** [BryanDonovan/node-cache-manager#107]
I have a use case where cache keys must manually be expired. How do i set the TTL so the cache never expires? If this is possible it should be documented.

**Comment by gswalden** [comment]
If you're asking about the built-in Memory cache, it's default state is to never expire over time. By default it will only store 500 keys, however.

**Comment by BryanDonovan** [comment]
Yeah, it depends on the underlying cache you're using.  E.g., with Redis, passing in no TTL will effectively make the cache entries never expire.

**Comment by johnmalatras** [comment]
Following up on this- ttl is required as part of the StoreConfig when calling cacheManager.caching(). Is there another way to have entries never expire?

**Comment by BryanDonovan** [comment]
@johnmalatras - I'm not sure what you mean by `StoreConfig`... is that for a particular memory store?

**Comment by johnmalatras** [comment]
It appears that caching() expects a StoreConfig when creating with an in-memory store

**Comment by BryanDonovan** [comment]
As far as I know, it doesn't require an in-memory store: https://github.com/BryanDonovan/node-cache-manager/blob/master/lib/stores/memory.js#L15

**Comment by johnmalatras** [comment]
Hmm I'm using Typescript and getting this: 

```
Argument of type '{ store: "memory"; max: number; }' is not assignable to parameter of type 'StoreConfig & CacheOptions'.
  Property 'ttl' is missing in type '{ store: "memory"; max: number; }' but required in type 'StoreConfig'.
```

where CachingConfig:
```
export interface CachingConfig {
    ttl: number | TtlFunction;
}
```

**Comment by BryanDonovan** [comment]
Oh, I don't use TypeScript -- someone else added the type definitions.  But I think you can just pass in `0` to have the cache never expire.

**Comment by johnmalatras** [comment]
Ah cool, thanks!
