### ISSUE TITLE
New warning on upgrade to bluebird 3.5.1

### ISSUE THREAD

**Issue by jeff-kilbride** [BryanDonovan/node-cache-manager#108]
I recently upgraded to bluebird 3.5.1 and am now seeing a lot of the following warnings in my logs:

```
(node:19) Warning: a promise was created in a handler at app/node_modules/cache-manager/lib/caching.js:52:21 but was not returned from it, see http://goo.gl/rRqMUw 
at new Promise (/app/node_modules/bluebird/js/release/promise.js:79:10)
```

I believe adding an explicit `return` to `caching.js:52` would remove the warning, i.e.:

```js
return cb(null, result);
```

Thanks!

**Comment by BryanDonovan** [comment]
Thanks Jeff.  Can you verify that your change fixes this?  I don't currently have any code using bluebird.

**Comment by jeff-kilbride** [comment]
Hi Bryan,

Actually, it doesn't, which is weird. But this does:

```js
cb(null, result);
return null;
```
I have created #109 with the fix.
