### ISSUE TITLE
isCacheableValue doesn't seem to work

### ISSUE THREAD

**Issue by wmertens** [BryanDonovan/node-cache-manager#110]
I just tracked down an issue where I used `isCacheableValue: Boolean` and it was still caching`false` key values. Doing the check manually before calling wrap fixes my issue.

```js
const memoryCache = cacheManager.caching({
	store: 'memory',
	isCacheableValue: Boolean,
	max: 100,
	ttl: 5 * 24 * 60 * 60 /* seconds */,
})

[...]

		const key = cacheKeyForReq(req, context)
		const resultP = cache.wrap(key, () => {
					console.log(
						key
							? `=== Caching page for ${key}`
							: `=== Pre-rendering page ${req.url}`
					)
					return prerenderApp(req, context)
				})
      resultP.then [...]
```

**Comment by BryanDonovan** [comment]
`isCacheableValue` checks the value, not the key.

**Comment by wmertens** [comment]
Oh wow, that explains a lot :) ok, I'll close, I guess, unless maybe this
needs to be explained better in the readme?

**Comment by BryanDonovan** [comment]
Yeah, please close.  I think the readme is pretty clear :)
