### ISSUE TITLE
keys()

### ISSUE THREAD

**Issue by nivthefox** [BryanDonovan/node-cache-manager#112]
As a developer, I would like a way to inspect all keys currently in the cache such that 
```javascript
function handleKeys (keys) {
   // do things here like check for stale keys that need to be cleaned
}

cache.keys((err, keys) => handleKeys(keys)); // callback signature
cache.keys().then(handleKeys); // promise singnature

**Comment by BryanDonovan** [comment]
Hi @kkragenbrink - there is a `keys` method in the `caching.js` module.  It simply maps to the underlying cache store's `keys` method, if it exists: https://github.com/BryanDonovan/node-cache-manager/blob/master/lib/caching.js#L179

**Comment by kkragenbrink** [comment]
@BryanDonovan It does not seem to work with multiCaching.  Is there a better way to achieve this?

**Comment by kkragenbrink** [comment]
I've implemented this locally as
```javascript
cache.keys = (callback) => {
    return new Promise((resolve, reject) => {
        Promise
            .map(caches, (cache) => {
                if (!cache.keys) return [];
                return cache.keys();
            })
            .reduce((arr, curr) => [...arr, ...curr], [])
            .then((keys) => {
                if (callback) return callback(null, keys);
                else resolve(keys);
            })
            .catch((err) => {
                if (callback) return callback(err);
                else reject(err);
            });
    });
```

I'm sure this is not the best approach, however.

**Comment by BryanDonovan** [comment]
I'm not sure either.  I think I'd call `keys()` individually on each cache in the multi-cache array, which is basically what you're doing.  I guess it depends on what you want to do with the keys, and whether that operation is different for each cache (it seems like it would be).
