### ISSUE TITLE
Feature request: key tags

### ISSUE THREAD

**Issue by josser** [BryanDonovan/node-cache-manager#120]
Hi! It would be very useful to specify 'tag' for keys, i.e: 
cache.set(key, value, { ttl, tags })

so if we want invalidate several keys simultaneously we can do something like:

cache.delByTag(tag)

**Comment by BryanDonovan** [comment]
Seems like that would be specific to a certain data store?

**Comment by josser** [comment]
I guess not. 
Maybe it's possible to do something like:
cache.set('key', value, {ttl, tags: ['foo'])
// cache.set('tag:foo', cache.get('tag:foo').push(key), { ttl })
// atomicity? 

cache.delTag('foo') 
// keys = cache.get('tag:foo')
// keys.forEach(key => cache.del(key))

**Comment by BryanDonovan** [comment]
I don't think this is feasible for this library to make it generic enough to work with any cache store.

**Comment by josser** [comment]
This is very common thing in caching libraries: 
http://symfony.com/doc/current/components/cache/cache_invalidation.html
https://github.com/ahawkins/cashier
https://framework.zend.com/manual/1.10/en/zend.cache.introduction.html

**Comment by josser** [comment]
If you take a look at http://symfony.com/doc/current/components/cache/cache_invalidation.html they have 'TagAwareAdapter' abstraction for this. So if backend storage can't support tags, developer should provide two adapters, one for tags and one for items.

**Comment by BryanDonovan** [comment]
Do you want to try to add this feature?  As long as it doesn't break any existing functionality and works with the existing adapters, it's fine with me.

**Comment by josser** [comment]
@BryanDonovan I'm not sure I have enough skills but I'll try )

**Comment by apetta** [comment]
Was this implemented in the end? Can't see anything relevant to tags in the docs
