### ISSUE TITLE
404 Not Found: lru-cache@https://registry.npmjs.org/lru-cache/-/lru-cache-4.0.0.tgz

### ISSUE THREAD

**Issue by lealceldeiro** [BryanDonovan/node-cache-manager#121]
I'm trying to do `npm install cache-manager --save` from the [documentation](https://github.com/BryanDonovan/node-cache-manager#installation) but I'm getting:

```
npm ERR! code E404
npm ERR! 404 Not Found: lru-cache@https://registry.npmjs.org/lru-cache/-/lru-cache-4.0.0.tgz

npm ERR! A complete log of this run can be found in:
npm ERR!     /<my-npm-debug-log>-debug.log
```

`.npmrc`

```
proxy=http://<proxy-ip>:<port>/
https-proxy=http://<proxy-ip>:<port>/
registry=http://registry.npmjs.org/
```
`node -v`: v8.11.3

How can I solve this issue?

**Comment by BryanDonovan** [comment]
This is probably something to do with your .npmrc file or it's a temporary issue with npm.  I just tried installing on my system and it worked fine.

**Comment by BryanDonovan** [comment]
To debug, try installing just lru-cache:
```
npm install lru-cache@4.0.0
```

**Comment by lealceldeiro** [comment]
Ok, thank for replying. I'll keep trying.

**Comment by BryanDonovan** [comment]
No problem!
