### ISSUE TITLE
memory store - updateAgeOnGet 

### ISSUE THREAD

**Issue by Java-Superman** [BryanDonovan/node-cache-manager#122]
It would be nice if the lib/stores/memory.js was changed to support updateAgeOnGet from the lru-cache.
see https://www.npmjs.com/package/lru-cache

**Comment by BryanDonovan** [comment]
Hi, I'm a bit a swamped at the moment, but would gladly accept a pull request.  Otherwise I might be able to get to this in the next few weeks.  Thanks!

**Comment by BryanDonovan** [comment]
Fixed in #136
