### ISSUE TITLE
remainingTTL

### ISSUE THREAD

**Issue by VinayaSathyanarayana** [BryanDonovan/node-cache-manager#123]
Is there a way to get remainingTTL in case of cache hit?
This could be useful to try prefetching

Note: 
https://www.npmjs.com/package/node-cache#get-ttl-getttl --> Provides Total TTL

I am looking for remainingTTL

**Comment by BryanDonovan** [comment]
Hi, 

This is implemented via the `ttl` method here: https://github.com/BryanDonovan/node-cache-manager/blob/master/lib/caching.js#L314

You would have to make a wrapper of your own with a `ttl` method that calls your underlying store's `getttl` method.

-Bryan
