### ISSUE TITLE
Breaking change in 2.10.2

### ISSUE THREAD

**Issue by jvasekpn** [BryanDonovan/node-cache-manager#132]
Hello, we have discovered a breaking change in a recent commit:
https://github.com/BryanDonovan/node-cache-manager/commit/84901cc118c628a141e27d1e05b66d230e0c917a

We use the memory store to cache closures which no longer works upon subsequent calls to `wrap`.  Here is an example of the bug:
![Screenshot_17](https://user-images.githubusercontent.com/45108468/73564108-85a64800-4424-11ea-98fd-2614bc5e50dd.png)

And here is an example of it working as expected in version 2.10.1:
![image](https://user-images.githubusercontent.com/45108468/73564123-8dfe8300-4424-11ea-8e79-3b677edd1555.png)

Doing a deep clone on a function returns an empty object.

**Comment by BryanDonovan** [comment]
Thanks for letting me know.  I've fixed this in version 2.10.3.

**Comment by jvasekpn** [comment]
Awesome, thanks for the heads-up.  We should have no problem waiting for the next release.

**Comment by BryanDonovan** [comment]
Oh, it's released already :)

**Comment by jvasekpn** [comment]
Epic, thanks!

**Comment by ryanbecker** [comment]
The cloning in 2.10.2 also causes objects to lose their prototype. This breaks https://github.com/AzureAD/passport-azure-ad, which caches a [Metadata](https://github.com/AzureAD/passport-azure-ad/blob/dev/lib/metadata.js) instance. I can understand if this is by design, in which case I'll follow up with `passport-azure-ad`.

**Comment by BryanDonovan** [comment]
@ryanbecker - Thanks for letting me know.  I think the best thing to do is for me to create a 3.0.0 release that makes the cloning optional/configurable.  

However, I do think it's odd to be caching anything other than data.  I.e., I would assume all cache stores would behave the same -- e.g., you couldn't store an object's prototype in redis.

**Comment by ryanbecker** [comment]
It actually looks like `lodash.deepClone` preserves the object's prototype, so I think 2.10.3 is where the prototype is lost during the clone.

**Comment by BryanDonovan** [comment]
@ryanbecker - do you have any code snippet that reproduces this?  I'd like to make a unit test case out of it.  Hopefully some kind of `clone` function will fix this problem and continue to fix the problem fixed in 2.10.2.

**Comment by ryanbecker** [comment]
Sure: https://github.com/BryanDonovan/node-cache-manager/pull/133. The test passes if I replace `deepMerge` with `lodash.cloneDeep`.

**Comment by jvasekpn** [comment]
> However, I do think it's odd to be caching anything other than data. I.e., I would assume all cache stores would behave the same -- e.g., you couldn't store an object's prototype in redis.

I do agree that the point of a cache is to store data, but I feel like the memory cache is a special case and has a marked advantage of being able to store nearly anything.  I really appreciate that kind of flexibility and I think that restricting the storage media to certain datatypes would be a downgrade to this NPM package.

Whatever you do, please don't remove the ability to store functions, arbitrary objects, etc in the memory store.

**Comment by BryanDonovan** [comment]
@jvasekpn - Yeah, I see that point.  I merged @ryanbecker's fix which is available now in release 2.11.1.
