### ISSUE TITLE
No tags for 3.1.0 - 3.3.0 Releases

### ISSUE THREAD

**Issue by gavingmiller** [BryanDonovan/node-cache-manager#143]
It's difficult to verify what is up on npm vs what is in the source code if version numbers don't align with tags. Seeing if source code aligns with versions is important for security, and a missing tag in a repo is sometimes a signal that a package has been compromised. It would be greatly appreciated if you could tag your releases in the future. :)

**Comment by BryanDonovan** [comment]
Sorry about that.  I just forgot to push the tags.  They're all pushed now.

**Comment by gavingmiller** [comment]
No prob! Thanks for pushing ❤️
