### ISSUE TITLE
How to disable cache in development?

### ISSUE THREAD

**Issue by fookit** [BryanDonovan/node-cache-manager#146]
Howdy! I'm using this in my Koa REST API. I set `ttl: 30` for `production`. 

But when in `development`, I don't want to use cache. I tried setting `ttl: NODE_ENV === Production ? 30 : 0`. It still caches first request. 

For instance, when I query at `localhost:3000/items` and it returns empty array `[]` first. Then I added an item and query `/items` again, it returns empty array `[]` first, then returns the correct result `[{id: 1}]` at second query.

```ts
...

export const cache = cacheManager.caching({
  ...
  ttl: isProduction ? 30 : 0,
})
```

Please help me, how do I do not to cache in `development`?

---

Stack: typescript, koa, cache-manager (v3.3.0), cache-manager-ioredis (v2.1.0)

**Comment by curtdept** [comment]
Set cache to null and do a falsey check before using it.

For example I do (isCloud is just a boolean env variable, could be anything):
const cache  = isCloud ? cacheManager.caching(redisOptions) : null;

then later...
if (cache) { }

**Comment by BryanDonovan** [comment]
Sorry for the delayed response.  Yeah, what @curtdept said.  You basically have to manually turn cache on or off.  Also, a `ttl` of `0` results in there being no `ttl` at all.

**Comment by curtdept** [comment]
@BryanDonovan the Async dep bump is mint btw :) much faster 👍

**Comment by BryanDonovan** [comment]
Oh, cool. I think someone else bumped it for a security reason.  Glad it's faster too..

**Comment by thatsaw** [comment]
Thank you :)

**Comment by fookit** [comment]
Thank you :)
