### ISSUE TITLE
No uniform way of defining an inifinite ttl

### ISSUE THREAD

**Issue by jbeaudoin11** [BryanDonovan/node-cache-manager#147]
I'm looking at the default memory store and the ioredis store and they don't behave the same way if ttl is set to 0.

I want to have a default ttl of 60 sec and 300 sec for memory and ioredis store respectively. That said, sometime i would like to have no ttl at all and never expire the key based on time only space. With ioredis you can set the ttl to 0 when setting the key. But the memory store doesn't understand 0 as infinite storage it just never cache the key and alwayse poke the next store instead in a multi store config.

Related to #107

**Comment by BryanDonovan** [comment]
Sorry, I can't do anything about how the underlying stores work..

**Comment by jbeaudoin11** [comment]
I mean you can define the behavior, up to the store to fit that behavior. Can define tests to make sure the behaviors are respected. Obviuously it's not your responsability to make the stores.

That said, the default memory store is problematic here if we assume 0 is infinite ttl. But i don't see this as the define behavior in the doc. Might be a good idea to add it to the doc if we want to do a store.

**Comment by BryanDonovan** [comment]
The problem is that I can't arbitrarily decide that a ttl of zero means infinite for all stores.  All we can do is pass it to the underlying store.  I didn't want to define the behavior of passing zero to lru-cache because they could change how it works and then cache-manager's docs would be wrong.  Still, I could clarify the docs.. I'll do that when I have a bit of spare time.

**Comment by jbeaudoin11** [comment]
Yeah i can see how now it's kinda too late. Maybe we could add a new parameter in the options ? like `noTtl` or something ?

**Comment by BryanDonovan** [comment]
How would `noTtl` work with lru-cache?

**Comment by jbeaudoin11** [comment]
The only way i see it is by setting maxAge in lru-cache to undefined at the start when you create the cache (new). It's cache-manager's responsability to keep the default arround and pass it each time you call set. Sounds a little hacky but it would work i think. Does it works with all stores :man_shrugging:.

I guess i can do that in my app.. But would be greate if cache-manager would do it for us instead of having to send a ttl for each set..

**Comment by BryanDonovan** [comment]
Hmm... actually, are you sure using `0` for `ttl` is not working? This example seems to work for me:

```javascript
const cacheManager = require('cache-manager');
const memoryCache = cacheManager.caching({store: 'memory', max: 100, ttl: 0});

function getUser(id, cb) {
    setTimeout(() => {
        console.log("Fetching user from slow database.");
        cb(null, {id: id, name: 'Bob'});
    }, 100);
}

const userId = 123;

function getCachedUser(id, cb) {
    memoryCache.wrap(id, cacheCallback => {
        getUser(id, cacheCallback);
    }, cb);
}

getCachedUser(userId, (err, user) => {
    // First time fetches the user from the (fake) database:
    console.log('Fetched user:', user);

    setTimeout(() => {
        getCachedUser(userId, (err, user) => {
            // Second time fetches from cache.
            console.log('Fetched user:', user);
            process.exit();
        });
    }, 1010);
});
```

The output is:

```
Fetching user from slow database.
Fetched user: { id: 123, name: 'Bob' }
Fetched user: { id: 123, name: 'Bob' }
```

(which shows that it's only fetching from the "database" once).

**Comment by jbeaudoin11** [comment]
I'm having some problem with the cache right now.. weird stuff is happening.. gonna make some test later this weekend.

i said 0 doesn't work because because the behavior isn't define in lru-cache.. maybe it does works

**Comment by jbeaudoin11** [comment]
@BryanDonovan I've done some testing and I relized that something doesn't look right, or at least not as intuitive as i would expect from a tiering cache system.

Lets say i have 2 processes, 1 local memory cache and a shared redis cache. If the process A set the key for `cache:1234` then process B try to access that key. The local cache of B misses, so it tries with the shared cache which hit so everything is fine. Now what should we expect from process **B** if i ask for the key again ? (lets forget ttls)

1. The local cache hit
2. The local cache miss again and the redis cache hit

I was expecting 1, but I think i'm getting 2. It looks like the higher priority cache isn't updated when there is a hit in a lower priority queue, only if all caches miss.

It's a little out of the scope of the original post, but i think this is why i tought the ttl 0 wasn't working with lru-cache since i get a miss everytime another process access a key that isn't in its local cache but is in the redis cache.

**Comment by BryanDonovan** [comment]
Yeah, it should get set in the local cache for B.  This test demonstrates that: https://github.com/BryanDonovan/node-cache-manager/blob/master/test/multi_caching.unit.js#L1693

**Comment by jbeaudoin11** [comment]
I think i found the source. I'm using get, not wrap.
```Javascript
context("when value exists in second store but not first", function() {
    it.only("returns value from second store, sets it in first store", async function() {
        await memoryCache3.set(key, { name:name });

        const widget = await multiCache.get(key);
        // const widget = await multiCache.wrap(key, (cb) => methods.getWidget(name, cb));

        assert.deepEqual(widget, {name: name});
    });
});
```
I didn't understand wrap at first so i was always using get/if/fetch/set.. But now i see what it is for !
That said, shouldn't get also update the higher priority stores ?

**Comment by BryanDonovan** [comment]
I left `get` to simply retrieve from cache and not do any implicit updates.  I could see the case to have it do an update as well, but that's really what `wrap` is for.

**Comment by jbeaudoin11** [comment]
Well it shouldn't be a problem now if i move to wrap which i'm planning todo.
And everything works with ttl 0.

Thanks for your support :heart: !
Not all repos are replying that fast :clap: !

**Comment by BryanDonovan** [comment]
No problem!
