### ISSUE TITLE
Some types are not correct (?)

### ISSUE THREAD

**Issue by MickL** [BryanDonovan/node-cache-manager#150]
I wonder if `@types/cache-manager` are correct. I found two things:

1. `cacheManager.set('key', { hello: 'world' })` is not possible because set requires at least 3 properties.

Suggestion:

```ts
set<T>(key: string, value: T): Promise<any>;
set<T>(key: string, value: T, options: CachingConfig): Promise<any>;
set<T>(key: string, value: T, ttl: number): Promise<any>;
set<T>(key: string, value: T, options: CachingConfig, callback: (error: any) => void): void;
set<T>(key: string, value: T, ttl: number, callback: (error: any) => void): void;
```

2. `.get()` accepts a generic but does not return it. Therefor typings are lost and the generic is useless: 

```ts
const cachedEntry = await cacheManager.get<MyInterface>('key');
// -> cachedEntry is of type any instead of MyInterface
```

Suggestion:

```
get<T>(key: string, callback: (error: any, result: T) => void): void;
get<T>(key: string): Promise<T>;
```

**Comment by MickL** [comment]
I created a PR

**Comment by BryanDonovan** [comment]
Thanks!

**Comment by MickL** [comment]
@BlackDark even updated more https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50600

**Comment by BlackDark** [comment]
@BryanDonovan can be closed.
See https://www.npmjs.com/package/@types/cache-manager/v/3.4.0
