### ISSUE TITLE
Feature: Delete keys based on regex

### ISSUE THREAD

**Issue by rubiin** [BryanDonovan/node-cache-manager#151]
It would be nice to have a feature to delete multiple keys based on a regex pattern.
This is a workaround i have been following
```
const keys = await this.cacheManager.store.keys();
const userCaches = keys.filter((el: string) => el.includes(pattern));
if (userCaches.length > 0) await this.cacheManager.del(userCaches);
```

**Comment by BryanDonovan** [comment]
This is too specific to the memory store.  I.e., not all stores have the ability to fetch the keys. I highly recommend writing your own store where you can implement whatever you want though.

**Comment by ZhaoKunLong** [comment]
AH. This is really useful for me, Thank you @rubiin

**Comment by RidhamShah** [comment]
What does `pattern` means for
`this.cacheManger.store.keys(pattern?: string)`
Is it in regex format?
