### ISSUE TITLE
[Proposal] - Official Stores for Redis and Memcached

### ISSUE THREAD

**Issue by rtablada** [BryanDonovan/node-cache-manager#16]
Coming in from other server-side languages and communities, I was a bit perplexed that there wasn't a good driver based system for Node.

I came across this package and was really excited.
However, I am a bit confused as to why you only have an in-memory store and not simple stores for Redis or Memcached?

I noticed the Redis example but was surprised that it is not available when pulling this in with NPM.

Would you be interested in bringing in configurable stores for these cache mechanisms?

**Comment by jkernech** [comment]
Hi,

I have published a separate module for the Redis store since I use it in multiple projects and I didn't want duplicate code : 

https://github.com/dial-once/node-cache-manager-redis
http://npmjs.com/package/cache-manager-redis

Hope this helps
Cheers !

**Comment by BryanDonovan** [comment]
Thanks @jkernech -- I'll add this to the README soon.

**Comment by BryanDonovan** [comment]
Sorry for the delay.  `node-cache-manager-redis` has been added to the README, along with `node-cache-manager-mongodb`.
