### ISSUE TITLE
How to check if the store is connected?

### ISSUE THREAD

**Issue by dheerajsh** [BryanDonovan/node-cache-manager#163]
Let's application have a health check API that also ensure that all external connection from the application are live and working for example DB or Cache.

I am using node cache manager with Redis store, There is no function that allows me to ping the store (I don't wanna get one static key from cache to check since keys are generated dynamically based on user's request)

I understand the store itself has to implement that function but first we need a function in the cache manager

**Comment by BryanDonovan** [comment]
This might be ok, but it might also be better as part of each store.  E.g.,

```javascript
const cacheManager = require('cache-manager');
const redisStore = require('some-redis-store');
const redisCache = cacheManager.caching({store: redisStore});

redisStore.checkHealth((err, result) => {
    if (err) {
      ....
    }
});
```

**Comment by dheerajsh** [comment]
Yes I agree, I am going to create an issue for redis-store and link it with it,
