### ISSUE TITLE
How to use dump and load API since built-in memory cache is  node-lru-cache

### ISSUE THREAD

**Issue by jeoy** [BryanDonovan/node-cache-manager#169]
https://github.com/isaacs/node-lru-cache 

![image](https://user-images.githubusercontent.com/6924980/140892647-f4a03b40-365b-487a-9850-80f98dcae02b.png)

Can we use dump API now or Will this API be supported in the future ?

**Comment by BryanDonovan** [comment]
We can't add these methods to the `caching` or `multiCaching` modules because these methods aren't very generic -- i.e., they don't exist in other stores like Redis.  However, it's easy to write your own cache store where you could add these methods. Then you could access them either directly via the store or by calling `cache.store.dump()`, etc.

**Comment by jeoy** [comment]
> We can't add these methods to the `caching` or `multiCaching` modules because these methods aren't very generic -- i.e., they don't exist in other stores like Redis. However, it's easy to write your own cache store where you could add these methods. Then you could access them either directly via the store or by calling `cache.store.dump()`, etc.

Hi Bryan, actually I cannot access these methods by simply calling `cache.store.dump()` when I use memory cache.  Because these methods doesn't bind in [memory.js](https://github.com/BryanDonovan/node-cache-manager/blob/master/lib/stores/memory.js).

Would you mind I add these methods as optional methods in `memory.js`? Since they aren't very generic.

**Comment by BryanDonovan** [comment]
That might be ok, but what do you mean by "optional" methods?

**Comment by jeoy** [comment]
oh,  I mean declare optional TS type

**Comment by BryanDonovan** [comment]
Oh ok.  Yeah, that would be fine.  To clarify, these methods should not be added to the `caching` or `multiCaching` modules, and only to the memory store.

**Comment by BryanDonovan** [comment]
This is available in version 3.5.0
