### ISSUE TITLE
Wrapped memory cache does not respect TTL

### ISSUE THREAD

**Issue by thorlarholm** [BryanDonovan/node-cache-manager#17]
The default memory cache only uses the TTL that is given when it is created, not the TTL that is given when used as part of a wrap call.

This seems like a common scenario in multi-tiered caches.

It seems like this is caused by lru-cache not using the TTL that wrap passes on to the set method.

**Comment by BryanDonovan** [comment]
Sorry I didn't back to you on this.  I just didn't see it somehow.  Yeah, it looks like it's just the way lru-cache works.  You'd have to use a different cache in order for the ttl to be respected.

**Comment by TheBeastLT** [comment]
I've just stumbled on this... So the `memory-store` caches everything indefinitely? Is there a better in-memory store, which respects ttl?
