### ISSUE TITLE
[Feature Request] - Support SCAN of Redis or at least "bad Keys*"

### ISSUE THREAD

**Issue by Meywether** [BryanDonovan/node-cache-manager#175]
Hi there :)
Thanks for this awesome package.

May I ask to improve this package by implementing the SCAN functionality of Redis ?

Because I want to find certain keys within my redis store by Pattern, and as I read here: KEYS * is bad: https://stackoverflow.com/questions/40854654/redis-node-delete-with-prefix-wildcard

Thank you in advance :)
Meywether

**Comment by BryanDonovan** [comment]
I don't think I want to add any more Redis-specific commands so we can keep the library generic.  However, I think you can do something like this as a workaround: 

```
caching.store.getClient().scan();

```
That's assuming you're using this as your redis store: https://github.com/dabroek/node-cache-manager-redis-store

**Comment by Meywether** [comment]
@BryanDonovan 
Thanks for your quick response, yes I use NestJS 8 and the mentioned lib but I get following error:
![image](https://user-images.githubusercontent.com/39849054/146239637-2b580841-8f7c-4f1d-95a9-f3a710930b10.png)


Can you tell me sth about this error ?

Thank you in advance !!! :)

**Comment by BryanDonovan** [comment]
Looks like you just need to pass some argument(s) to the `scan` method.

**Comment by Meywether** [comment]
This is available in redis ( with get it is "catchable ):
![image](https://user-images.githubusercontent.com/39849054/146240214-ffe450a9-2c6e-4361-81fc-4c14a48ab767.png)
This is my query '/api/*'
![image](https://user-images.githubusercontent.com/39849054/146240458-a5d71a04-3b21-4ca2-8322-5c297c21ae8d.png)
Thank you :)

**Comment by Meywether** [comment]
aha, i am one step further 👍 
![image](https://user-images.githubusercontent.com/39849054/146243016-b4c9f969-99a8-43e2-85c0-77ecdc7c436d.png)

Please leave this open, if i have questions, I will close it afterwards or will tell you if any questions arises :)

**Comment by BryanDonovan** [comment]
Looks like the `scan` method has an odd signature.  See https://github.com/redis/node-redis/blob/v3.1/examples/scan.js#L9

**Comment by Meywether** [comment]
ah nice, thanks I will dive into and provide a sample of working code for your docs :)

**Comment by Meywether** [comment]
Greets @BryanDonovan 
figured it out :)
Really strange syntax, as you mentioned ^^
If you want, you can close ist 

```js
  async getKeysByCID(cid: string): Promise<void> {
    await this.cache.store
       // eslint must be disabled because getClient() is not a defined function in generic lib but in redis available
      // eslint-disable-next-line @typescript-eslint/ban-ts-comment
      // @ts-ignore
      .getClient()
      .scan(0, 'MATCH', `/api/v1/companies/${cid}/*`, (err, res) => {
        const cursor = res[0];
        const keys = res[1];
        if (keys.length > 0) {
          console.log('Array of matching keys', keys);
        }
        if (cursor === '0') {
          return console.log('Iteration complete');
        }
        return this.getKeysByCID(cid);
      });
  }
```

**Comment by BryanDonovan** [comment]
Good to hear!
