### ISSUE TITLE
Use multiple in-memory cache

### ISSUE THREAD

**Issue by meetachanchlani** [BryanDonovan/node-cache-manager#176]
Hi I am currently using an in-memory cache and Redis cache as the node-cache-manager provides. I want to add a third tier as well after Redis which should be an in-memory cache. Can I implement it with the existing library or is it not possible?

**Comment by BryanDonovan** [comment]
Yeah, you should be able to do that by adding the third store to the array like this:

```javascript
 cacheManager.multiCaching([memoryCache, redisCache, someOtherCache]);
```

**Comment by meetachanchlani** [comment]
Thanks for the quick response. Also, does the order in which cache is passed determine the priority. 
For example if I do cacheManager.multiCaching([memoryCache1, redisCache, memoryCache2]);
Will memoryCache1 have the first priority and memoryCache2 the least?

**Comment by BryanDonovan** [comment]
Yep, that's right -- the order determines priority.

**Comment by meetachanchlani** [comment]
Do you think this order is possible? 
Memory Store 1 -> Redis -> Real function -> Memory Store 2
