### ISSUE TITLE
Cache Manager TTL -1

### ISSUE THREAD

**Issue by meetachanchlani** [BryanDonovan/node-cache-manager#177]
Hi I am trying to use an in-memory Cache with cache-manager:

cache = cacheManager.caching({ store: 'memory', ttl: -1 })
await cache.set(key, value, { ttl: -1 });

I don't want the keys to expire ever. What is the ttl value I should use in case of in-memory?
For Redis it is -1 but when I try to use in this case, it doesn't set the key at all.

**Comment by BryanDonovan** [comment]
You should be able to pass in either no ttl (or null ttl) or pass in `0`.

**Comment by meetachanchlani** [comment]
Thanks, Sorry for the inconvenience but what does the ttl that is passed while creating the cache signify?
cache = cacheManager.caching({ store: 'memory', ttl:0 })

**Comment by BryanDonovan** [comment]
No problem.  In the case of the memory store, it gets passed as `maxAge` to `LRUCache`: https://github.com/BryanDonovan/node-cache-manager/blob/master/lib/stores/memory.js#L36

A `maxAge` of `0` in `LRUCache` tells the cache to not set a `maxAge` (ttl) by default.  It can be overridden on individual `set` calls.
