### ISSUE TITLE
Clear or refresh the cache regularly

### ISSUE THREAD

**Issue by Zachary-zm** [BryanDonovan/node-cache-manager#178]
Excuse me.  How to clear the cache regularly？

**Comment by BryanDonovan** [comment]
That depends on what underlying cache you’re using. You would need to clear the cache using whatever method it provides, not through node-cache-manager.

**Comment by Zachary-zm** [comment]
> That depends on what underlying cache you’re using. You would need to clear the cache using whatever method it provides, not through node-cache-manager.

OK，thank you. I find it used node-lru-cache, but i have no idea how to clear it regularly

**Comment by BryanDonovan** [comment]
In that case, see: https://github.com/BryanDonovan/node-cache-manager/blob/084ee381b7108be06b39bcbaa5f5dd73d54d1340/lib/stores/memory.js#L169

**Comment by BryanDonovan** [comment]
Ok to close this?

**Comment by Zachary-zm** [comment]
> Ok to close this?

I'm very sorry, I forgot it！

**Comment by BryanDonovan** [comment]
No problem!
