### ISSUE TITLE
TypeScript types missing `Promise` support for `.wrap` function

### ISSUE THREAD

**Issue by moshest** [BryanDonovan/node-cache-manager#180]
Currently the type definition contain the following declaration for the `wrap` function:

```ts
export type WrapArgsType<T> = 
  | string 
  | ((callback: CallbackFunc<T>) => void) 
  | CachingConfig 
  | CallbackFunc<T>; // <- invalid type


export interface Cache {
  wrap<T>(...args: WrapArgsType<T>[]): Promise<T>;
}
```

However, this declaration doesn't support promises. I think the correct definition should be something like this:

```ts
export type WrapArgsType<T> = 
  | string 
  | ((callback: CallbackFunc<T>) => void)
  | CachingConfig 
  | (() => PromiseLike<T> | T); // <- correct type


export interface Cache {
  wrap<T>(...args: WrapArgsType<T>[]): Promise<T>;
}
```

(Note I replaced `CallbackFunc<T>` with `() => PromiseLike<T> | T`)

How can we fix this?

**Comment by BryanDonovan** [comment]
Hi. The TypeScript types are managed in a different repo by someone else: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/cache-manager

**Comment by moshest** [comment]
PR opened here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/58974
