### ISSUE TITLE
Memory Size Limit For In-Memory Cache

### ISSUE THREAD

**Issue by AnkDos** [BryanDonovan/node-cache-manager#182]
Hello , 

Is there any option available to set the size limit of the in-memory cache or setting the maxSize for the items in the cache ?

**Comment by BryanDonovan** [comment]
Yes, you can pass in `max` for the max size of the cache and `maxAge` for maximum age.

**Comment by AnkDos** [comment]
Max represents the item count or the memory size(say in byte) ?

**Comment by BryanDonovan** [comment]
That param is passed to node-lru-cache: https://github.com/isaacs/node-lru-cache#usage

**Comment by AnkDos** [comment]
As mentioned in the above doc , "The maximum number (or size) of items that remain in the cache" . I am bit confused that whether the input will be considered as the number of items or the size of item .

**Comment by BryanDonovan** [comment]
The `max` param corresponds to the maximum number of items in the cache.  I agree, the wording in the docs is confusing.  Also, we're using Lru-cache version 6.0.0, which have different docs: https://github.com/isaacs/node-lru-cache/tree/v6.0.0#options

You can also pass in a `length` function to indicate how an item is counted toward the `max` limit.  But in version 7.0.0, they added a `maxSize` param and changed the name of the `length` function.  

The tests for version 6 might be helpful: https://github.com/isaacs/node-lru-cache/blob/v6.0.0/test/basic.js#L45

**Comment by AnkDos** [comment]
Thanks !
