### ISSUE TITLE
Can't make nested calls to a wrapped function

### ISSUE THREAD

**Issue by BryanDonovan** [BryanDonovan/node-cache-manager#21]
The `cache.wrap()` function can't be called multiple times in series (nested).  E.g., this no longer works (from examples/redis_example/example.js):

```javascript
function get_cached_user(id, cb) {
    memory_cache.wrap(id, function(cache_callback) {
        get_user(id, cache_callback);
    }, cb);
}

get_cached_user(user_id, function(err, user) {
    // First time fetches the user from the (fake) database:
    console.log(user);

    get_cached_user(user_id, function(err, user) {
        // Second time fetches from cache.
        console.log(user);
    });
});
```

This started failing in commit 46459ff1a7d689461f3f6acd6d7fa01bd099640b

**Comment by BryanDonovan** [comment]
@aletorrado, I've found that if I wrap the callbacks with `process.nextTick()`, it solves this problem.  Can you please check out branch `feature/nested-cache-fetch-fix` and check that I didn't break anything for your use cases?  The diff is https://github.com/BryanDonovan/node-cache-manager/commit/c9cd9773408299921ca3a0ef242af590e3ebb80f

**Comment by BryanDonovan** [comment]
I'm not sure this fix is correct.  It seems like magic.  This line where we delete the queued callbacks: https://github.com/BryanDonovan/node-cache-manager/compare/feature/nested-cache-fetch-fix#diff-4144c5c2a16b6a217fc942aee2803138R59

.. happens before the callbacks are called.  Maybe this makes sense though.

**Comment by aletorrado** [comment]
Hi @BryanDonovan. The problem was that one of the final callbacks was updating the self.queues[key] array, while iterating. Your solution is correct, but you may also want to try something like this:

        function fillCallbacks(err, data) {
            var waiting = self.queues[key];
            delete self.queues[key];
            waiting.forEach(function(task) {
                var taskDomain = task.domain || domain.create();
                taskDomain.bind(task.cb)(err, data);
            });
        }

**Comment by BryanDonovan** [comment]
Thanks, I was thinking of something similar as well. I'll give that a try.

**Comment by aletorrado** [comment]
Nice job. Thanks.
