### ISSUE TITLE
Multiple requests during first cache

### ISSUE THREAD

**Issue by gmaclennan** [BryanDonovan/node-cache-manager#23]
How does the wrap function handle multiple concurrent requests to the same key when the value still is not cached? E.g.

```js
function getCachedUser(id, cb) {
    memoryCache.wrap(id, function (cacheCallback) {
        getUser(id, cacheCallback);
    }, ttl, cb);
}
```

If `getUser()` takes 500ms to respond and you call `getCachedUser(123, cb)` 10 times before 500ms has passed, does it make 10 calls to `getUser()` because the value is not cached until the first `getUser()` returns?

**Comment by BryanDonovan** [comment]
It queues up the callbacks until one of them returns, then it fires the remaining callbacks.  Most of that logic is here: https://github.com/BryanDonovan/node-cache-manager/blob/master/lib/callback_filler.js, which is called from: https://github.com/BryanDonovan/node-cache-manager/blob/master/lib/caching.js#L46

**Comment by BryanDonovan** [comment]
.. the test for that is: https://github.com/BryanDonovan/node-cache-manager/blob/master/test/multi_caching.unit.js#L664

**Comment by BryanDonovan** [comment]
I updated the test to make it a bit more realistic (make the first call slower than subsequent), just in case. https://github.com/BryanDonovan/node-cache-manager/commit/44b31ae761990fe61d670d32a97c200a798c3ed3

**Comment by gmaclennan** [comment]
That's great to know. I'd tried reading the code but couldn't quite get my head around it. Should have looked at the tests! Thanks.
