### ISSUE TITLE
Numbers with value 0, booleans with value false are not cached using wrap

### ISSUE THREAD

**Issue by PuKoren** [BryanDonovan/node-cache-manager#25]
When method inside wrap callbacks with false or 0 as parameter, the cache is not used and the next call to wrap launch the method again
Is it expected behaviour?

**Comment by BryanDonovan** [comment]
That's a good point.  I'll fix that.

**Comment by PuKoren** [comment]
Thanks for your quick answer

**Comment by BryanDonovan** [comment]
This is available in the latest `develop` branch (see https://github.com/BryanDonovan/node-cache-manager/compare/develop).  I want to make a few more updates before the next release, so I won't publish this to npm quite yet.  Can you please give the develop branch a try and see if it fixes the issue for you?

Thanks!

**Comment by BryanDonovan** [comment]
This is available in 1.0.0 release.

**Comment by PuKoren** [comment]
Thanks for the fix and sorry for the delay
Unfortunately, redis returns null when data is not present, and this is considered as valid value for cache.
I made a PR there: https://github.com/BryanDonovan/node-cache-manager/issues/29 but this implies a lot of stuff and multi caching may be a pain.

Is it ok for you to consider undefined AND null should not be stored as valid cached value? So we can still store 0 and false.

Cheers
