### ISSUE TITLE
Multi-Store potentially returning incorrect value

### ISSUE THREAD

**Issue by yanickrochon** [BryanDonovan/node-cache-manager#32]
I am replacing our current cache solution with this project and, while sniffing through the code to understand it's implementation, I came across [these lines](https://github.com/BryanDonovan/node-cache-manager/blob/master/lib/multi_caching.js#L46-L49) :

```
if (result) {
  // break out of async loop.
  return cb(err, result, i);
}
```

Which will fail if the stored value is *falsy* (`null`, `0`, `false`, `''`, etc.) which is not correct. The condition should be changed to `if (result !== undefined) { ... }` instead, no?

**Comment by BryanDonovan** [comment]
Thanks for letting me know!  I've fixed in version 1.2.0.
