### ISSUE TITLE
TTL Issues

### ISSUE THREAD

**Issue by ronenteva** [BryanDonovan/node-cache-manager#40]
First, thanks for a great plugin.

In some of your examples you show:
`multiCache.set('foo2', 'bar2', {ttl: ttl}, function(err) {`
and in others:
`multiCache.set('foo2', 'bar2', ttl, function(err) {`

I noticed that redis only respects the first setting, and mongo doesn't respect neither.

**Comment by BryanDonovan** [comment]
Thanks for this.  I'll update the examples.  It should be the `{ttl: ttl}` version.
