### ISSUE TITLE
cross-process caches

### ISSUE THREAD

**Issue by TrevorNWatson** [BryanDonovan/node-cache-manager#45]
I'm uncertain if this is a possibility, or even a good process.

I have a RESTful service running in Express that has multiple instances through pm2.  

I use your library to create an in-memory cache for various items in the project, and use the file-cache package to save a token / credentials for a user on disk.  The reason I do this separately is I am afraid that a client request may hop between processes (it shouldn't, but it could).

For example:
Client authenticates, gets dashboard, sits idle for 2 minutes, goes to client page, gets different server.   At this point their token is no longer valid as the token seems to exist only on the first process they were on.   

I was hoping creating a common folder with the processes all pointing to it might create a "shared" cache, but this doesn't seem to be the case.  If I authenticate in one browser, then switch browsers, I have to re-authenticate (different process).   If I run a single process, this isn't the case, I can switch between browsers fine as they all go to the same process.

Is it possible to have a "shared" cache between two processes in this case?

Thank you in advance.

**Comment by BryanDonovan** [comment]
It probably depends on how pm2 is creating separate processes.  If it's "manually" running two separate processes, I can't think of any way to do this with an in-memory cache.  But if it's running a master process and forking a child process from it, you could share the cache between the processes.  

I haven't used this, but it might work for you if you are forking a child process: https://github.com/robby/node-lru-cache-cluster
You'd have to create your own wrapper for it, similar to https://github.com/BryanDonovan/node-cache-manager/blob/master/lib/stores/memory.js, but change `lru-cache` to `lru-cache-cluster`.

It would be worth a shot I think.

**Comment by TrevorNWatson** [comment]
It looks like pm2 actually creates individual processes for each instance.  Thanks for your quick response!

**Comment by BryanDonovan** [comment]
No problem!
