### ISSUE TITLE
feature: cache size

### ISSUE THREAD

**Issue by amit777** [BryanDonovan/node-cache-manager#50]
It would be awesome to be able to get the current size in bytes of all the items that have been added or expired from the cache.  Is it as simple as keeping a counter that is incremented whenever an item is added, deleted or expired?  Maybe it could be an instantiation option like  trackSize: true

**Comment by BryanDonovan** [comment]
I think this would be specific to whatever store you're using, so you could probably add that functionality there.  E.g., it wouldn't make sense for a redis store.
