### ISSUE TITLE
caching of Buffer()

### ISSUE THREAD

**Issue by amit777** [BryanDonovan/node-cache-manager#52]
I've noticed a discrepancy when caching a Buffer (such as for an image).  The memory cache set/get work fine.  However, on Redis or the FS cache modules, get returns a JSON string like this:

```
{"type":"Buffer","data":[65,66,67,68,69,70,71]}
```

Just wondering if there is a suggested way of handling this.  Should the modules themselves store metadata in the cache that a buffer was stored as a value and then deserialize it?  Or should there be an options flag in the cache-manager set command that indicates it's caching a buffer.

**Comment by BryanDonovan** [comment]
I think this would be something that you implement in your store.  I don't think cache-manager is manipulating this data anywhere that I know of.

**Comment by amit777** [comment]
got it.. so probably just need to create an option in the underlying storage module that understands that a Buffer is getting set.  It seems like cache-manager alreayd supports sending custom options, so I will work with the redis and fs module maintainers with a pull request.

**Comment by BryanDonovan** [comment]
Cool, sounds good.
