### ISSUE TITLE
Cache Timeout

### ISSUE THREAD

**Issue by alexspence** [BryanDonovan/node-cache-manager#53]
Using this module along with the redis cache manager store.  If redis is down, currently the cache will just hang forever instead of returning an error.  This could be considered a bug in the redis store, but if we had a way to add a timeout to the cache calls, it would solve the problem for us.

**Comment by BryanDonovan** [comment]
This is likely useful.  Do you want to try adding this?  If not, I can probably get to it in the next week or so.

**Comment by alexspence** [comment]
I can take a stab at it.

**Comment by alexspence** [comment]
I ended up rolling my own cache implementation as I needed more control over the redis integration.

**Comment by BryanDonovan** [comment]
Sounds good, thanks!

**Comment by RickWong** [comment]
If anyone finds this thread and is still using `node-cache-manager-redis` then you can fix this by specifying a no-op `retry_strategy` (which is an underlying `sol-redis-pool` option):

````js
cache = cacheManager.caching({ 
  store: cacheRedis, 
  max: 128,/*items*/ 
  ttl: 600,/*seconds*/ 
  retry_strategy: () => undefined, /*don't reconnect to redis at all*/ 
});
````

Warning: Do try to use a [retry_strategy](https://www.npmjs.com/package/sol-redis-pool#a-simple-reconnect-strategy) in production.
