### ISSUE TITLE
Move es6-promise from devDependencies to dependencies

### ISSUE THREAD

**Issue by raviagrwl** [BryanDonovan/node-cache-manager#54]
Using the `wrap` method with a Promise breaks when no global `Promise` is defined. Although since you have `es6-promise` in your devDependencies all your tests pass.

**Comment by BryanDonovan** [comment]
How are you using Promises?  I was assuming people would use a poly-fill to set `globals.Promise`.  e.g.,

```javascript
require('es6-promise').polyfill();
```

**Comment by raviagrwl** [comment]
We explicitly require the promise library, in our case it is `bluebird`, and don't rely on the `Promise` global.    I think it would make sense to include a promise library as dependency and use it in case `global.Promise` is not found.

**Comment by neeharv** [comment]
Another option would be to allow an optional Promise polyfil to be passed into the constructor. That way, this should work with any A+ compliant Promise library without an additional dependency being installed. So in our case, we wouldn't need `es6-promise` as a dependency if we already have `bluebird`. h/t @siddharthkchatterjee for this suggestion.

**Comment by BryanDonovan** [comment]
Good idea.  I like the idea of passing in the Promise dependency.

**Comment by siddharthkchatterjee** [comment]
@BryanDonovan, take a look at #55 please.
