### ISSUE TITLE
CallBack_filler error

### ISSUE THREAD

**Issue by randeepbhatia** [BryanDonovan/node-cache-manager#57]
Hi
I am getting a cache error even after the http response has been sent
/*/node_modules/cache-manager/lib/callback_filler.js:9
    waiting.forEach(function(task) {
           ^

TypeError: Cannot read property 'forEach' of undefined
    at CallbackFiller.fill (/*/node_modules/cache-manager/lib/callback_filler.js:9:12)
    at /*/node_modules/cache-manager/lib/caching.js:117:44
    at nextTickCallbackWith0Args (node.js:419:9)
    at process._tickDomainCallback (node.js:389:13)

Not sure if it is because of cache-manager or not. 
Can you kindly help.

**Comment by BryanDonovan** [comment]
I've seen this before but don't remember what caused it.  Can you narrow down the code that reproduces the error?

**Comment by randeepbhatia** [comment]
I did narrow it down. Let me give you some background.
I have been using this as a layer between api-router & db.js. Multiple api calls use this cache. I am using  memoryCache.wrap() function to cache the request. But what is surprising, even if i disable the cache, it still raises exception. 
We can take this conversation offline also, if you prefer.
Thanks for the help though.

**Comment by randeepbhatia** [comment]
Resolved it.

**Comment by BryanDonovan** [comment]
Cool.  Was it related to the cache?

**Comment by randeepbhatia** [comment]
It was related to the application, where the return statement isn't provided after the data retrieval. Hence the code continues to execute and the item gets cached twice. I think there should be an error handling in the cache module to handle that, rather than making the app crash.

**Comment by BryanDonovan** [comment]
Good idea.  This is fixed in version 2.1.2 now.  Thanks!
