### ISSUE TITLE
Not returning cached value between script calls

### ISSUE THREAD

**Issue by Jakobud** [BryanDonovan/node-cache-manager#59]
Perhaps I am confused on how this library works.... but I'm trying the example here, but using the filesystem store:

```
var cacheManager = require('cache-manager');
var fsStore = require('cache-manager-fs');
var diskCache = cacheManager.caching({
    store: fsStore, options: {
      ttl: 60*60,
      maxsize: 1000*1000*1000,
      path: 'diskcache',
      preventfill: true
    }
  });

var ttl = 30;

function getUser(id, cb) {
    setTimeout(function () {
        console.log("Returning user from slow database.");
        cb(null, {id: id, name: 'Bob'});
    }, 5000);
}

var userId = 123;
var key = 'user_' + userId;

// Note: ttl is optional in wrap()
memoryCache.wrap(key, function (cb) {
    getUser(userId, cb);
}, {ttl: ttl}, function (err, user) {
    console.log(user);

    // Second time fetches user from memoryCache
    memoryCache.wrap(key, function (cb) {
        getUser(userId, cb);
    }, function (err, user) {
        console.log(user);
    });
});
```

Okay so, I have my `getUser` method, that simulates a database taking 5 seconds to return the value from the database.

When I run the script, it runs `getUser()`, then it caches it for `ttl = 30` seconds. And then it does `getUser` again and returns the value immediately.

Okay so that works fine.

But then if I run the script again, right away, it does not initially fetch the `getUser` value from the filesystem store. Instead it runs `getUser` again and then caches it again to a second .dat file on the server.

Why doesn't it go fetch the value from the cache when I run the script a second time? I do it within 30 seconds, which is what the `ttl` is set to and the `key` (`user_123`) doesn't change between the script calls.

The whole point of caching is so that after a value is cached, subsequent script calls (or web requests) fetch the cached value instead of running `getUser()` each time. Does this library only cache things when they are within a single script call? If so, what is the point of the filesystem store?

Am I just completely misunderstanding how to use this?

**Comment by BryanDonovan** [comment]
This is how the `cache-manager-fs` store works.. it's per-process as far as I can tell.  So each time you run the script, which creates a new process, it also creates a new `.dat` file.

**Comment by BryanDonovan** [comment]
In other words, if you have a server running on one process, the caching will work like expected until you restart the server.  At that point it will create a new `.dat` file.

**Comment by BryanDonovan** [comment]
I haven't tried it myself, but maybe this store would work for multiple processes: https://github.com/sheershoff/node-cache-manager-fs-binary

**Comment by Jakobud** [comment]
So if I have some external process, like a cronjob that needs to access the cache data and make some changes several times per day, there is no way to do this?

**Comment by BryanDonovan** [comment]
Yeah, I don't know why the fs file store does it like that (I didn't write it).  It seems odd to me, or maybe there's a config option that will let the cache be shared by multiple processes.

**Comment by BryanDonovan** [comment]
To clarify, if you used the redis store, mongo store, etc. the cache would be shared across processes.

**Comment by BryanDonovan** [comment]
It happens because of this line:

https://github.com/hotelde/node-cache-manager-fs/blob/master/index.js#L172

You might want to fork that project and submit a pull request with a change that lets you override that uuid part.  Basically let you pass in a `filename` param.

CC @hotelde

**Comment by Jakobud** [comment]
Thanks for the help. I've been messing with it's code. Some console.log's tell me that it seems to be finding the proper .dat file on startup and it's finding the data, but that data just isn't filled into the cache. Not sure what I'm doing wrong. Thank you for the help,

**Comment by Jakobud** [comment]
Here is my issue I've opened over there for reference

https://github.com/hotelde/node-cache-manager-fs/issues/9

**Comment by BryanDonovan** [comment]
No problem.
