### ISSUE TITLE
Is getAndPassUp used?

### ISSUE THREAD

**Issue by PuKoren** [BryanDonovan/node-cache-manager#61]
I'm trying to implement a new feature on `node-cache-manager`, and I have stepped into the `getAndPassUp` method. I have trouble finding where it is used, as I can't see any reference to it in the project, except in tests.

It is used?

**Comment by BryanDonovan** [comment]
It's not used elsewhere in the code, but it was added by @raadad in this PR: https://github.com/BryanDonovan/node-cache-manager/pull/19

Presumably he uses it for something.

**Comment by raadad** [comment]
*Sorry for the late reply.

If a higher level of cache does not have an item but a lower level does, it will pass up that item into the higher level.

This is to cover for events when ttl's are different between caching layers and is very noticeable in clustered environments as one server ends up refreshing the lower level of cache but all others wont refresh their higher levels.
