### ISSUE TITLE
High performance/availability cache setup - feature request

### ISSUE THREAD

**Issue by PuKoren** [BryanDonovan/node-cache-manager#62]
Hello!

I'm currently adding a new feature to node-cache-manager. However I am not sure of the way to go yet, because I can't find a consistent API for the available stores.

The idea of the feature request is to add an always available, low latency multi store setup. This way even if our frontend server loses connection to backend for whatever reason, it will keep working at maximum speed for our front users.

Idea for the high perf/high availability setup using node-cache-manager:

> Using a multi store, and wrap method
> - First store have a TTL of 0 (always resolve, keep data forever)
> - Secondary stores have a TTL > 0 (fetched from it if not in primary store, expires after TTL)
> - When data expires from secondary store, data is still returned immediately from first store, while secondary store is being updated, once done primary store will be updated too.

However, since API of stores is not defined, I can't have access to TTL, expired date/time of keys, etc. and of course I don't want to call `.get` on each store every time wrap is called, to check if it contains the key in order to update it.

Any idea on how to implement this in an efficient manner?

Feature specs available here: https://github.com/dial-once/node-cache-manager/commit/9948303260b1e89967629f9489bd2759a3c0ffba

**Comment by BryanDonovan** [comment]
Are you saying you need methods like `cacheStore.getTtl()`?

**Comment by PuKoren** [comment]
Something like that, for a given key. It will be needed for this feature

I can add it to memory cache, as well as redis cache, but for other caches it may cause the feature to not work because this method wont be available. Any idea for this?

**Comment by BryanDonovan** [comment]
I suppose this could just be added like it is in `caching.js`:

```javascript
    /**
     * Binds to the underlying store's `ttl` function if it exists.
     * @function
     * @name ttl
     */
    if (typeof self.store.ttl === 'function') {
        self.ttl = self.store.ttl.bind(self.store);
    }
```

Your new feature should probably check if the `ttl` function exists before trying to use it.. or maybe throw an error so it fails hard.

**Comment by PuKoren** [comment]
Thanks for your answer, I will assume that `.ttl` function is required for this feature then. I would like to keep backward compatibility so I don't think I will throw any error, but rather disabling the feature if `ttl` function is undefined on one of the stores.

**Comment by BryanDonovan** [comment]
I think this sounds good.  This should probably be something a user enables via config.  Something like `autoUpdateLowerPriorityCaches: true` (hopefully you can think of a better name though).

**Comment by PuKoren** [comment]
Ok, will go for a config var then, thanks for your inputs!

**Comment by amit777** [comment]
@PuKoren I was looking to do something almost exactly the same (in fact your solution sounds better than what I was thinking). Did you end up creating something for this?
