### ISSUE TITLE
Is there a way to invalidate/expire/delete a cache manually?

### ISSUE THREAD

**Issue by prabhg** [BryanDonovan/node-cache-manager#64]
I have some cached data that is no longer relevant in certain scenarios. I want to therefore be able to invalidate cache before its ttl expires so that next time data is requested, it would be refetched and recached. Is there presently an api to drop particular cached data by its "id"?

**Comment by srgl** [comment]
What about `cache.del(id)` ?

**Comment by BryanDonovan** [comment]
Yes, assuming the `id` is the same as the cache key, you can call `cache.del(id)`.
