### ISSUE TITLE
purge?

### ISSUE THREAD

**Issue by bonesoul** [BryanDonovan/node-cache-manager#76]
is cache purge functionality available?

**Comment by BryanDonovan** [comment]
It isn't right now, mainly because each cache implementation has different ways of doing this, if they have any way at all.

**Comment by bonesoul** [comment]
maybe you should letting implementations functionality to implement this?

**Comment by BryanDonovan** [comment]
Sorry, I'm not sure what you mean.

**Comment by bonesoul** [comment]
i have elaborated my question.

**Comment by BryanDonovan** [comment]
Oh, I guess we do have a purge function, called `reset`: https://github.com/BryanDonovan/node-cache-manager/blob/master/lib/caching.js#L165

It isn't guaranteed that a third-party engine would implement it though. (see also: https://github.com/BryanDonovan/node-cache-manager/issues/73)
