### ISSUE TITLE
Postgres support?

### ISSUE THREAD

**Issue by kevin-daniel-hunt** [BryanDonovan/node-cache-manager#77]
I'd love to be able to use this cache manager with my postgres backend.  I have been watching this page for some time but it seems no one has done a postgres manager yet.  Unfortunately I don't quite have the know-how to do it so just putting it out there that it would be a huge support!

**Comment by josser** [comment]
You better don't use relational db as a cache.
The idea of cache is in its 'locality' principle, so it should be faster than original resource. 
IMHO, relational database is one of the slowest resource
I'd suggest to use (in order of speed): local memory, local memcache/redis, networked redis/cache.
