### ISSUE TITLE
Question: are calls waiting for the first to complete?

### ISSUE THREAD

**Issue by tkarls** [BryanDonovan/node-cache-manager#78]
I think this module is a perfect match to use in my app. I just want to double check one thing. 

If I have a wrapped function and calls it 5 times before the wrapped async function has completed  then all 5 calls will wait for the wrapped function to complete and return the same value. I.e the slow async function is only called once?

I understand this is the case when something already is cached. But question is calls made while the cache entry is being calculated.

**Comment by BryanDonovan** [comment]
The way it works is all the calls are added to a queue, and none of them return until the wrapped function returns the first time.  So it only calls the wrapped function once, even if it's really slow.

**Comment by tkarls** [comment]
Thanks for you answer. It was what I hoped for :)

I have integrated the module in my app now and it works perfect! Easy to use and great syntax for wrapping promise based functions. 5 star!

**Comment by BryanDonovan** [comment]
No problem, thanks!
