### ISSUE TITLE
delete does not return a promise

### ISSUE THREAD

**Issue by kkragenbrink** [BryanDonovan/node-cache-manager#79]

**Comment by BryanDonovan** [comment]
In what situation are you seeing this?

**Comment by kkragenbrink** [comment]
An in-memory datastore.   So something like:

```javascript
const CacheManager = require('cache-manager');
const cache = CacheManager.caching({store: 'memory'});

cache.set('foo', 1)
    .then(() => cache.get('foo'))
    .then((val) => console.log(val)) //1
    .then(() => cache.del('foo'))
    .then(() => cache.get('foo')) // throws an error. Expected a promise in return
    .then((val) => console.log(val)) // expect undefined
```

**Comment by BryanDonovan** [comment]
Thanks.  I added a test for this and it passes for me.  I also tried your exact example and it didn't throw an error.  Here's the commit with the test: https://github.com/BryanDonovan/node-cache-manager/commit/04e6333857faec23fd84042491f547a534ea13f0

Can you check out the latest master branch and see if the tests pass for you?

**Comment by kkragenbrink** [comment]
Seems to work.  Still doesn't work in my specific case, but I suppose I'll assume id10t error, at this point.  Thanks!
