### ISSUE TITLE
get call stuck when redis server is down 

### ISSUE THREAD

**Issue by gargvk10** [BryanDonovan/node-cache-manager#87]
I have encountered a case where when i am making a get call to redis store in multicache it get stuck because redis store is not throwing the connection error as the redis client does. Although redis connection pool of redis store emits events "redisError" if it is not able to make the connection but using this event we cannot make our call sync in case of fallback to original calls to db rather then redis in case of connection failure.

**Comment by BryanDonovan** [comment]
I would either write my own redis store with code that listens for these events, or file an issue with https://github.com/dial-once/node-cache-manager-redis.
