### ISSUE TITLE
Cache stampede problem

### ISSUE THREAD

**Issue by kretz** [BryanDonovan/node-cache-manager#88]
Hi,

Is there a "dog piling" aka "stampede" problem when a key has expired and multiple calls want to read that key?

Let me describe in detail what I mean first.

First, let's say we have an expensive network call `fetchResource` which takes about 10s and it is wrapped with `wrap`:

```
function getResource(id) {
  return resourceCache.wrap(key, () => {
    return fetchResource(id); // takes 10s
  });
}
```

Second, let's say the cache is empty, or the key has expired, and we get 1000 calls to `getResource` within 10s. What will happen then? Will we see 1000 `fetchResource` calls?

Is there a recommended way to get out of that situation? 

A way I was thinking about would be to detect if there is an ongoing request and return the promise associated with that request, instead of creating a new call to `fetchResource`. Would that work?

Thanks,
Martin

**Comment by BryanDonovan** [comment]
Hi Martin,

I've never tested this with that many calls, but it *should* handle it in theory.  The way it works is each request for a given key gets added to a queue.  Then when the slow call finishes, the result is passed to each callback in the queue.
