### ISSUE TITLE
Wrap on multi-caching

### ISSUE THREAD

**Issue by yoavbaruch** [BryanDonovan/node-cache-manager#90]
Hello,

in file lib/multi_caching.js line 242, I think that not calling callbackFiller.fill(key, err, data) on non cacheable values, can cause queued callbacks to hang.

**Comment by BryanDonovan** [comment]
Thanks.  Maybe this is related to https://github.com/BryanDonovan/node-cache-manager/issues/89

**Comment by BryanDonovan** [comment]
Fixed in 2.6.0
