### ISSUE TITLE
Best way to implement a cache enabled/disabled flag with wrap

### ISSUE THREAD

**Issue by alecl** [BryanDonovan/node-cache-manager#92]
I need to be able to turn off the cache easily for debugging purposes. I'm doing something like this now but there has to be a cleaner way to do this than below repeating the getUser call twice. Suggestions?

```
var cacheEnabled = false;

function getCachedUser(id, cb) {
    if (cacheEnabled) {
      memoryCache.wrap(id, function (cacheCallback) {
          getUser(id, cacheCallback);
      }, {ttl: ttl}, cb);
    } else {
      getUser(id, cb);
    }
}
```

**Comment by BryanDonovan** [comment]
Sorry for the delayed response.  I disabled flag might be ok to add.  Do you want to submit a pull request?
