### ISSUE TITLE
Can a new value be calculated before the old expired?

### ISSUE THREAD

**Issue by tkarls** [BryanDonovan/node-cache-manager#93]
I have an app that has a function that takes a second or two to calculate (querying external servers and processes).

I'm using the cache-manager today and when accessing my app I get:

Slow (initial call. Of course it will be slow)
fast (since in cache now)
fast
fast
fast
fast
slow (since value expired)
fast
fast
fast
fast
slow

etc.

Now, is it somehow possible to start calculating the new value while still returning the old one. Like if I could set up a TTL = 10 seconds. New Calc = 8 seconds. That would give the user calling the function on second 9 a fast reply since value is still in cache but it would also trigger a recalculation so the user calling at second 11 also gets a fast response.

Once the new value is calculated it will replace the old one even if the full ttl isn't expired yet.

Can this be achieved somehow today with multi level caching or some other way?

**Comment by raadad** [comment]
I wrote this to facilitate this and some othe features:

https://github.com/raadad/node-cachemire/blob/master/index.js

**Comment by raadad** [comment]
Basically looking for options.cacheRefreshThreshold

**Comment by BryanDonovan** [comment]
Hmm.. I'm not sure how to go about implementing this, but I'm happy to accept a pull request.

**Comment by raadad** [comment]
I can try PR the following features:

// IMMENENT EXPIRY UPDATE * the feature being requested here
// UPSTREAM COALESSING 
// STAGGERED TTL

I wrote a wrapper library for cache manager, but I think people could benefit from these features

**Comment by tkarls** [comment]
Interesting @raadad 
I might take a look at your wrapper. Although if you are able to PR the feature here and its accepted than that would be just super!
