### ISSUE TITLE
del() & reset() don't return a Promise when using multi-caching 

### ISSUE THREAD

**Issue by seoker** [BryanDonovan/node-cache-manager#97]
As I tested and traced the code, `del` and `reset` don't seem to return a `Promise` when using multi-caching.

**Comment by BryanDonovan** [comment]
Interesting.  This was brought up before here: https://github.com/BryanDonovan/node-cache-manager/issues/79

**Comment by hugoduraes** [comment]
I've noticed a similar issue on here:
https://github.com/dabroek/node-cache-manager-redis-store/issues/5

**Comment by dabroek** [comment]
I've added promise support for `del`, `reset`, and `ttl` in dabroek/node-cache-manager-redis-store.
