### ISSUE TITLE
Ttl for InMemory cache

### ISSUE THREAD

**Issue by jainh** [BryanDonovan/node-cache-manager#98]
I noticed that default ttl for LRU cache and set function with ttl  not respecting ttl, is this expected behavior ?

**Comment by BryanDonovan** [comment]
I'm not sure I understand what you mean.  Can you provide an example please?

**Comment by jainh** [comment]
`const memoryCache =  cacheManager.caching({store: 'memory', max:100, ttl: 1/*seconds*/});`
this is my cache with default ttl
then in set `Cache.prototype.put = (key, value, ttl = 1) => {
  memoryCache.set(key, value, {ttl:ttl});
};`
i am setting up ttl, i am trying to access key after 1 seconds but it is still there or if i set value with 0 ttl, again i hit the cache.

**Comment by BryanDonovan** [comment]
The `ttl` should be working.. this function seems correct: https://github.com/BryanDonovan/node-cache-manager/blob/master/lib/stores/memory.js#L21 (maybe I'm missing something though).

I don't know why it wouldn't work.  I'm really busy with work this week but might be able to look into this next week.  In the meantime, if you'd like to create a pull request with a test that demonstrates the issue, that would help a lot.

**Comment by jainh** [comment]
Test was simple as follows
```
cache.set("keyWithTtl","value",1);

 setTimeout(cache.get("keyWithTtl", (err, result) => {
        assert(err !== null, "`Non-Null` for the error ");
        assert(result === null);
        done();
      }), 2000);

```

something along that line.

**Comment by BryanDonovan** [comment]
Thanks.  I can hopefully look into this next week.  Otherwise if you want to submit a pull request with a fix, I'll gladly accept it.

**Comment by gswalden** [comment]
I don't think there is an issue here, see this example:

```js
const assert = require('assert');
const cacheManager = require('cache-manager');
const cache = cacheManager.caching({ store: 'memory', max: 100, ttl: 1 });
cache.set("defaultTTL", true);
cache.set("customTTL", true, 2);

setTimeout(() => {
  cache.get("defaultTTL", (err, result) => {
    assert.ifError(err);
    assert(!result);
  })
}, 2000);

setTimeout(() => {
  cache.get("customTTL", (err, result) => {
    assert.ifError(err);
    assert(!result);
  });
}, 3000);
```

The test code in https://github.com/BryanDonovan/node-cache-manager/issues/98#issuecomment-302119585 is not valid, as the `setTimeout` code calls the cache immediately, instead of waiting for the timeout to expire.

**Comment by BryanDonovan** [comment]
Thanks @gswalden.  @jainh - Can I close this?

**Comment by jainh** [comment]
Yes thank you!
