### ISSUE TITLE
From another .js file of node server cache is undefined

### ISSUE THREAD

**Issue by chsukhesh** [BryanDonovan/node-cache-manager#99]
In my project i set memory cache in one .js file. It gives cache with in the file only. when i try to get cache from another .jf file it show result is undefined. 

Can you help me, How can i set cache set as global for getting entire node server.
Thank you.

**Comment by BryanDonovan** [comment]
You probably just need to `require()` the file.

**Comment by chsukhesh** [comment]
can you please give a example.
you mean get the cache variable into new js file

**Comment by BryanDonovan** [comment]
I might not be understanding the issue, but I'm guessing you have something like:

`cache.js`:
```javascript
const cacheManager = require('cache-manager');
const memoryCache = cacheManager.caching({store: 'memory', max: 100, ttl: 10/*seconds*/});

// some custom code.. e.g.,

const myCacheModule = {
   myFunc(args, cb) {
      memoryCache.get ....
   }
 // etc.
};

module.exports = myCacheModule;
```

Then in another file:

```javascript
const myCacheModule = require('./cache');
// do stuff..
```

**Comment by chsukhesh** [comment]
Thank you very much but,
What i am doing is -
 
A.js

       var cacheManager = require('cache-manager');
       var memoryCache = cacheManager.caching({store: 'memory', max: 1000, ttl: 90/*seconds*/});
        memoryCache.set(mobileNo,user, {ttl: ttl}, function(err) {
            if (err) {
                callback({'Error':true,'Message':err});
                console.log('error of user repo',err);
             }else {
                console.log("SucessFully added to cashe");
                callback(undefined,"SucessFully added to cashe");
            }
 
            });



B.js

           var cacheManager = require('cache-manager');
           var memoryCache = cacheManager.caching({store: 'memory', max: 1000, ttl: 90/*seconds*/});

           memoryCache1.get('8978719458', function(err, result) {
            if(err){
                callback({'Error':true,'Message':"session is end"});
                console.log('session is end',err);
            }
            else{
                console.log(result);
                callback(undefined,result);
            }
        });

**Comment by BryanDonovan** [comment]
You can make a third file that just exports your `memoryCache` instance.  E.g.,

myMemoryCache.js

```javascript
var cacheManager = require('cache-manager');
var memoryCache = cacheManager.caching({store: 'memory', max: 1000, ttl: 90/*seconds*/});

module.exports = memoryCache;
```

Then from A.js and B.js, just require that file:

```javascript
var memoryCache = require('./myMemoryCache.js');

```

**Comment by chsukhesh** [comment]
Thank you very much, It's perfectly working.

**Comment by BryanDonovan** [comment]
No problem!
